def lieux(text):
    if(text=='Nice'):
        ville="nice-cote-d-azur"
    elif(text=='Lyon'):
        ville="lyon-st-exupery"
    elif(text=="Paris"):
        ville="paris-montsouris"
    elif(text=="Brest"):
        ville="brest-guipavas"
    elif(text=="Lille"):
        ville="lille-lesquin"
    elif(text=="Strasbourg"):
        ville="strasbourg-entzheim"
    elif(text=="Toulouse"):
        ville="toulouse-francazal"
    elif(text=="Rennes"):
        ville="rennes-st-jacques"
    elif(text=="Marseille"):
        ville="marseille-marignane-marseille-provence"
    elif(text=="Aix-en-Provence"):
        ville="aix-en-provence"
    elif(text=="Perpignan"):
        ville="perpignan-rivesaltes"
    elif(text=="Grenoble"):
        ville="grenoble-st-geoirs"
    elif(text=="Bordeaux"):
        ville="bordeaux-merignac"
    elif(text=="Nîmes"):
        ville="nimes-courbessac"
    elif(text=="Cannes"):
        ville="cannes"
    elif(text=="Angers"):
        ville="angers-beaucouze"
    elif(text=="Avignon"):
        ville="avignon"
    elif(text=="Dijon"):
        ville="dijon-longvic"
    elif(text=="Clermont-Ferrand"):
        ville="clermont-ferrand-audlnat"
    elif(text=="Biarritz"):
        ville="biarritz-anglet"
    elif(text=="Metz"):
        ville="metz-frescaty"
    elif(text=="Orléans"):
        ville="orleans-bricy"
    elif(text=="Annecy"):
        ville="annecy-meythet"
    elif(text=="Troyes"):
        ville="troyes-barberey"
    elif(text=="Pau"):
        ville="pau-uzein"
    elif(text=="Quimper"):
        ville="quimper-pluguffan"
    elif(text=="Caen"):
        ville="cean-carpiquet"
    elif(text=="Rouen"):
        ville="rouen-boos"
    elif(text=="Limoges"):
        ville="limoges-bellegarde"
    return ville 